import { Service } from "@tsed/common";
import { Logger } from "@tsed/logger";
import { parseRepoUrl } from "../domain/WorkspaceManager";
import { GITHUB_TOKEN } from "../config/env";

@Service()
export class GitHubService {
    private logger = new Logger("GitHubService");

    async createPullRequest(
        repoUrl: string,
        branchName: string,
        title: string,
        body: string
    ): Promise<string | null> {
        const { owner, repo } = parseRepoUrl(repoUrl);
        try {
            const { Octokit } = await import("@octokit/rest");
            const octokit = new Octokit({ auth: GITHUB_TOKEN });

            const response = await octokit.rest.pulls.create({
                owner,
                repo,
                title,
                body,
                head: branchName,
                base: "main",
            });
            return response.data.html_url;
        } catch (e: any) {
            this.logger.error(`PR creation failed: ${e.message}`);
            return null;
        }
    }

    async generatePRDescription(
        git: any,
        taskDescription: string,
        validationResult: { success: boolean; output: string; languages?: string[] }
    ): Promise<string> {
        try {
            // Get git diff stats between main and HEAD
            const diffStats = await git.diffSummary(["main"]);
            const filesChanged = diffStats.files?.length || 0;
            const insertions = diffStats.insertions || 0;
            const deletions = diffStats.deletions || 0;

            // Count test files
            const testFiles =
                diffStats.files?.filter(
                    (f: any) =>
                        f.file?.includes(".test.") ||
                        f.file?.includes(".spec.") ||
                        f.file?.includes("tests/") ||
                        f.file?.includes("__tests__/")
                ).length || 0;

            // Parse validation results
            const validationSummary: string[] = [];
            const output = validationResult.output;

            if (output.includes("Biome")) {
                validationSummary.push(
                    output.includes("✓") || output.includes("pass") ? "✅ Biome" : "⚠️ Biome"
                );
            }
            if (output.includes("TSC") || output.includes("TypeScript")) {
                validationSummary.push(
                    output.includes("✓") || output.includes("0 error") ? "✅ TSC" : "⚠️ TSC"
                );
            }
            if (output.includes("Ruff")) {
                validationSummary.push(
                    output.includes("✓") || output.includes("pass") ? "✅ Ruff" : "⚠️ Ruff"
                );
            }
            if (output.includes("Mypy")) {
                validationSummary.push(
                    output.includes("✓") || output.includes("Success") ? "✅ Mypy" : "⚠️ Mypy"
                );
            }
            if (output.includes("Trivy")) {
                validationSummary.push(
                    output.includes("✓") || output.includes("0 vulnerabilities")
                        ? "✅ Trivy"
                        : "⚠️ Trivy"
                );
            }

            const sections: string[] = [];

            if (taskDescription && taskDescription.trim()) {
                sections.push(`## Task Description\n\n${taskDescription.trim()}`);
            }

            sections.push("## Changes Summary\n");
            sections.push(`- **Files changed:** ${filesChanged}`);
            sections.push(`- **Insertions:** +${insertions}`);
            sections.push(`- **Deletions:** -${deletions}`);
            if (testFiles > 0) {
                sections.push(`- **Test files:** ${testFiles} modified/added`);
            }

            if (validationSummary.length > 0) {
                sections.push("\n## Validation\n");
                sections.push(validationSummary.join(" • "));
            }

            sections.push(
                "\n---\nGenerated by [Ralph Platform](https://github.com/Replikanti/ralph-platform)"
            );

            return sections.join("\n");
        } catch (error) {
            this.logger.warn("Failed to generate PR description:", error);
            return taskDescription || "Implementation completed by Ralph";
        }
    }
}
