import { logger } from '../infra/logger';
import { Langfuse } from "langfuse";
import { setupWorkspace, parseRepoUrl } from "./workspace";
import { runPolyglotValidation, detectProjectLanguages } from "./tools";
import { runClaude } from '../infra/claude-runner';
import fsPromises from 'node:fs/promises';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import type { AgentResult } from '../domain/types';

const langfuse = new Langfuse();

// --- TYPES ---

export interface Task {
    ticketId: string;
    title: string;
    description?: string;
    repoUrl: string;
    branchName: string;
    jobId: string;
    attempt: number;
    maxAttempts: number;
    mode?: 'full' | 'plan-only' | 'execute-only';
    existingPlan?: string;
    additionalFeedback?: string;
    isIteration?: boolean; // Flag indicating this is a PR iteration (fix request)
}


interface IterationContext {
    workDir: string;
    homeDir: string;
    task: Task;
    availableSkills: string;
    git: any;
    trace: any;
}

// --- HELPERS ---

async function summarizeFailurePhase(task: Task, _homeDir: string, errors: string): Promise<string> {
    try {
        const { b } = await import('../infra/baml');
        const { redactText } = await import('../security/redactor');
        const result = await b.SummarizeFailure({
            validationOutput: await redactText(errors.substring(0, 2000)),
            attempt: task.attempt,
            maxAttempts: task.maxAttempts,
        });
        return result.summary;
    } catch {
        return "Task failed due to persistent validation errors.";
    }
}

function getValidationSummary(output: string): string[] {
    const summary: string[] = [];
    if (output.includes('Biome')) {
        summary.push(output.includes('✓') || output.includes('pass') ? '✅ Biome' : '⚠️ Biome');
    }
    if (output.includes('TSC') || output.includes('TypeScript')) {
        summary.push(output.includes('✓') || output.includes('0 error') ? '✅ TSC' : '⚠️ TSC');
    }
    if (output.includes('Ruff')) {
        summary.push(output.includes('✓') || output.includes('pass') ? '✅ Ruff' : '⚠️ Ruff');
    }
    if (output.includes('Mypy')) {
        summary.push(output.includes('✓') || output.includes('Success') ? '✅ Mypy' : '⚠️ Mypy');
    }
    if (output.includes('Trivy')) {
        summary.push(output.includes('✓') || output.includes('0 vulnerabilities') ? '✅ Trivy' : '⚠️ Trivy');
    }
    return summary;
}

async function generatePRDescription(
    workDir: string,
    git: any,
    taskDescription: string,
    validationResult: { success: boolean; output: string; languages?: string[] }
): Promise<string> {
    try {
        const diffStats = await git.diffSummary(['main']);
        const filesChanged = diffStats.files?.length || 0;
        const insertions = diffStats.insertions || 0;
        const deletions = diffStats.deletions || 0;

        const testFiles = diffStats.files?.filter((f: any) =>
            f.file?.match(/\.(test|spec)\.|tests\/|__tests__\//)
        ).length || 0;

        const validationSummary = getValidationSummary(validationResult.output);

        const sections: string[] = [];
        if (taskDescription?.trim()) {
            sections.push(`## Task Description\n\n${taskDescription.trim()}`);
        }

        sections.push(
            `## 📊 Changes Summary\n`,
            `- **Files changed:** ${filesChanged}`,
            `- **Insertions:** +${insertions}`,
            `- **Deletions:** -${deletions}`
        );

        if (testFiles > 0) {
            sections.push(`- **Test files:** ${testFiles} modified/added`);
        }

        if (validationSummary.length > 0) {
            sections.push(
                `\n## ✅ Validation\n`,
                validationSummary.join(' • ')
            );
        }

        sections.push(`\n---\n🤖 Generated by [Ralph Platform](https://github.com/Replikanti/ralph-platform)`);

        return sections.join('\n');
    } catch (error) {
        logger.warn({ err: error }, '⚠️ Failed to generate PR description');
        return taskDescription || 'Implementation completed by Ralph';
    }
}

async function createPullRequest(repoUrl: string, branchName: string, title: string, body: string): Promise<string | null> {
    const { owner, repo } = parseRepoUrl(repoUrl);
    try {
        const { Octokit } = await import("@octokit/rest");
        const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
        
        const response = await octokit.rest.pulls.create({
            owner,
            repo,
            title,
            body,
            head: branchName,
            base: 'main', 
        });
        return response.data.html_url;
    } catch (e: any) {
        logger.error("PR failed: " + e.message);
        return null;
    }
}

export { RateLimitError } from '../infra/claude-runner';

async function listAvailableSkills(workDir: string): Promise<string> {
    // List native commands from .claude/commands so the Planner knows what's available
    const skillsDir = path.join(workDir, '.claude', 'commands');
    try {
        const dirs = await fsPromises.readdir(skillsDir, { withFileTypes: true });
        return dirs
            .filter((d: fs.Dirent) => d.isDirectory())
            .map((d: fs.Dirent) => `- /${d.name}`)
            .join('\n');
    } catch { return "No native commands available."; }
}

async function withTrace<T>(name: string, metadata: Record<string, any>, fn: (span: any) => Promise<T>) {
    const trace = langfuse.trace({ name, metadata });
    try { return await fn(trace); } 
    catch (e: any) { 
        trace.update({ metadata: { error: e.message } });
        throw e; 
    } 
    finally { await langfuse.flushAsync(); }
}

async function planPhase(_workDir: string, _homeDir: string, task: any, availableSkills: string, previousErrors?: string) {
    const { b } = await import('../infra/baml');
    const { redactText } = await import('../security/redactor');
    const result = await b.PlanTask({
        title: await redactText(task.title),
        description: await redactText(task.description ?? ''),
        skills: availableSkills,
        previousErrors: previousErrors ? [await redactText(previousErrors)] : [],
    });
    return result.plan;
}

async function executePhase(workDir: string, homeDir: string, plan: string) {
    const prompt = "You are the Executor. Implement this plan strictly: " + plan + "\n" +
        "RULES: No secrets, stay in sandbox, only necessary files, do not commit.";
    return await runClaude([
        '-p', prompt, 
        '--model', 'sonnet', 
        '--tools', 'Bash,Read,Edit,FileSearch,Glob',
        '--dangerously-skip-permissions', 
        '--permission-mode', 'bypassPermissions',
        '--max-budget-usd', '2.00', // Hard limit for one execution attempt
        '--no-session-persistence'
    ], workDir, homeDir, 900000);
}

const CLAUDE_CACHE_ROOT = process.env.CLAUDE_CACHE_PATH || '/app/claude-cache';
if (!fs.existsSync(CLAUDE_CACHE_ROOT)) {
    try { fs.mkdirSync(CLAUDE_CACHE_ROOT, { recursive: true }); } catch (e: any) {
        logger.warn("Could not create cache root: " + e.message);
    }
}

async function syncDirectoryContents(sourceDir: string, targetDir: string, operation: string): Promise<void> {
    if (!fs.existsSync(sourceDir)) return;

    await fsPromises.mkdir(targetDir, { recursive: true });
    const { execSync } = await import('node:child_process');
    try {
        execSync("cp -r " + sourceDir + "/* " + targetDir + "/");
        logger.info(operation + " Claude projects cache");
    } catch (e: any) {
        logger.warn(operation + " failed: " + e.message);
    }
}

async function seedClaudeCache(targetClaudeDir: string) {
    const projectsCache = path.join(CLAUDE_CACHE_ROOT, 'projects');
    const targetProjects = path.join(targetClaudeDir, 'projects');
    await syncDirectoryContents(projectsCache, targetProjects, "Seeded");
}

async function persistClaudeCache(sourceClaudeDir: string) {
    const projectsSource = path.join(sourceClaudeDir, 'projects');
    const targetProjects = path.join(CLAUDE_CACHE_ROOT, 'projects');
    await syncDirectoryContents(projectsSource, targetProjects, "Persisted");
}

async function prepareClaudeSkills(workDir: string, homeDir: string) {

    const targetSkillsDir = path.join(homeDir, '.claude', 'commands');

    const sourceSkillsDir = path.join(workDir, '.claude', 'commands');

    const targetScriptsDir = path.join(homeDir, '.claude', 'scripts');

    const sourceScriptsDir = path.join(workDir, '.claude', 'scripts');



    try {

        if (await fsPromises.stat(sourceSkillsDir).then(() => true).catch(() => false)) {

            await fsPromises.mkdir(targetSkillsDir, { recursive: true });

            await fsPromises.cp(sourceSkillsDir, targetSkillsDir, { recursive: true });

        }

        if (await fsPromises.stat(sourceScriptsDir).then(() => true).catch(() => false)) {

            await fsPromises.mkdir(targetScriptsDir, { recursive: true });

            await fsPromises.cp(sourceScriptsDir, targetScriptsDir, { recursive: true });

        }

        logger.info("Loaded commands into isolated Claude environment");

    } catch (e: any) {

        logger.warn("Failed to load commands: " + e.message);

    }

}





async function runIteration(iteration: number, ctx: IterationContext, previousErrors: string): Promise<{ success: boolean, output?: string, agentResult?: AgentResult }> {
    logger.info("🤖 Iteration " + iteration);

    const planSpan = ctx.trace.span({ name: "Planning-Opus-Iter-" + iteration, metadata: { iteration } });
    const rawPlan = await planPhase(ctx.workDir, ctx.homeDir, ctx.task, ctx.availableSkills, previousErrors);
    const plan = rawPlan.replaceAll('<plan>', '').replaceAll('</plan>', '').trim();
    planSpan.end({ output: plan });

    const execSpan = ctx.trace.span({ name: "Execution-Sonnet-Iter-" + iteration, metadata: { iteration } });
    await executePhase(ctx.workDir, ctx.homeDir, plan);
    execSpan.end();

    const validationSpan = ctx.trace.span({
        name: "Validation",
        metadata: { iteration }
    });

    const check = await runPolyglotValidation(ctx.workDir);

    validationSpan.end({
        output: check.output,
        metadata: {
            success: check.success,
            languages: check.languages,
            toolResults: check.toolResults,
            totalErrors: check.totalErrors,
            relevantErrors: check.relevantErrors
        }
    });

    if (check.success) {
        logger.info("✅ Validation passed!");
        await ctx.git.add('.');
        const status = await ctx.git.status();
        if (status.staged.length > 0) {
            await ctx.git.commit("feat: " + ctx.task.title);
            const pushArgs = ctx.task.isIteration ? [] : ['--force'];
            await ctx.git.push('origin', ctx.task.branchName, pushArgs);

            let prUrl: string | null = null;
            if (!ctx.task.isIteration) {
                const prBody = await generatePRDescription(ctx.workDir, ctx.git, ctx.task.description || '', check);
                prUrl = await createPullRequest(ctx.task.repoUrl, ctx.task.branchName, "feat: " + ctx.task.title, prBody);
            }
            return { success: true, agentResult: { mode: 'full', status: 'executed', prUrl, isIteration: ctx.task.isIteration ?? false } };
        } else {
            logger.warn("⚠️ No files changed.");
            return { success: true, agentResult: { mode: 'full', status: 'no-changes' } };
        }
    }
    logger.warn("⚠️ Validation failed (Iter " + iteration + "):\n" + check.output);
    return { success: false, output: check.output };
}

async function setupClaudeEnvironment(targetClaudeDir: string, workDir: string, homeDir: string): Promise<string> {
    await fsPromises.mkdir(targetClaudeDir, { recursive: true });
    const sourceClaudeDir = path.join(os.homedir(), '.claude');

    try {
        await copyClaudeCredentials(sourceClaudeDir, targetClaudeDir);
        await configureClaudeSettings(targetClaudeDir);
        await ensureClaudeCredentialsExist(targetClaudeDir);
    } catch (e: any) {
        logger.warn("Seed failed: " + e.message);
    }

    await seedClaudeCache(targetClaudeDir);
    await prepareClaudeSkills(workDir, homeDir);
    return await listAvailableSkills(workDir);
}

async function copyClaudeCredentials(sourceDir: string, targetDir: string): Promise<void> {
    const files = ['.credentials.json', 'settings.json'];
    for (const f of files) {
        const src = path.join(sourceDir, f);
        const dst = path.join(targetDir, f);
        if (fs.existsSync(src)) {
            await fsPromises.copyFile(src, dst);
        }
    }
}

async function configureClaudeSettings(targetClaudeDir: string): Promise<void> {
    const settingsFile = path.join(targetClaudeDir, 'settings.json');
    let settings: any = {};

    if (fs.existsSync(settingsFile)) {
        try {
            settings = JSON.parse(await fsPromises.readFile(settingsFile, 'utf-8'));
        } catch {
            settings = {};
        }
    }

    if (!settings.mcpServers) {
        settings.mcpServers = {};
    }

    settings.mcpServers.toonify = {
        command: "node",
        args: ["/app/dist/mcp-toonify.js"]
    };

    await fsPromises.writeFile(settingsFile, JSON.stringify(settings, null, 2));

    const toonifyConfig = path.join(targetClaudeDir, 'toonify-config.json');
    if (!fs.existsSync(toonifyConfig)) {
        await fsPromises.writeFile(toonifyConfig, JSON.stringify({
            "enabled": true,
            "minTokensThreshold": 50,
            "minSavingsThreshold": 30,
            "skipToolPatterns": ["Bash", "Write", "Edit"]
        }, null, 2));
    }
}

async function ensureClaudeCredentialsExist(targetClaudeDir: string): Promise<void> {
    const credsFile = path.join(targetClaudeDir, '.credentials.json');
    if (!fs.existsSync(credsFile)) {
        await fsPromises.writeFile(credsFile, JSON.stringify({ "token": "dummy", "email": "ralph@duvo.ai" }));
    }
}

async function runFullMode(task: Task, workDir: string, homeDir: string, git: any, trace: any, availableSkills: string, targetClaudeDir: string): Promise<AgentResult> {
    let previousErrors = "";
    for (let i = 0; i < 3; i++) {
        const result = await runIteration(i + 1, { trace, workDir, homeDir, task, availableSkills, git }, previousErrors);
        await persistClaudeCache(targetClaudeDir);
        if (result.success && result.agentResult) {
            return result.agentResult;
        }
        previousErrors = result.output || "Unknown error";
    }
    const failureSummary = await summarizeFailurePhase(task, homeDir, previousErrors);
    return { mode: 'full', status: 'validation-failed', validationOutput: previousErrors, failureSummary };
}

// Helper to detect task type for Langfuse tracking
function detectTaskType(title: string): string {
    const lower = title.toLowerCase();
    if (lower.includes('fix') || lower.includes('bug')) return 'bugfix';
    if (lower.includes('refactor')) return 'refactor';
    if (lower.includes('test')) return 'test';
    if (lower.includes('doc')) return 'docs';
    return 'feature';
}

export const runAgent = async (task: Task): Promise<AgentResult> => {
    const mode = task.mode || 'full';
    const planReviewEnabled = process.env.PLAN_REVIEW_ENABLED !== 'false';
    const actualMode = (mode === 'full' && planReviewEnabled) ? 'plan-only' : mode;

    logger.info(`🎯 Running agent in mode: ${actualMode}`);

    // Setup workspace first to detect languages
    const { workDir, rootDir, git, cleanup } = await setupWorkspace(task.repoUrl, task.branchName);

    // Detect project languages for Langfuse tracking
    const detectedLanguages = await detectProjectLanguages(workDir);

    return withTrace("Ralph-Task", {
        ticketId: task.ticketId,
        mode: actualMode,
        languages: detectedLanguages,
        repository: task.repoUrl,
        taskType: detectTaskType(task.title)
    }, async (trace: any): Promise<AgentResult> => {
        const homeDir = path.join(rootDir, 'home');
        const targetClaudeDir = path.join(homeDir, '.claude');

        try {
            const availableSkills = await setupClaudeEnvironment(targetClaudeDir, workDir, homeDir);

            if (actualMode === 'plan-only') {
                return await handlePlanOnlyMode(task, workDir, homeDir, trace, availableSkills);
            }

            if (actualMode === 'execute-only') {
                if (!task.existingPlan) {
                    throw new Error("execute-only mode requires existingPlan");
                }
                return await handleExecuteOnlyMode(task, workDir, homeDir, git, trace, task.existingPlan);
            }

            return await runFullMode(task, workDir, homeDir, git, trace, availableSkills, targetClaudeDir);
        } finally {
            cleanup();
        }
    });
};

async function handlePlanOnlyMode(
    task: Task,
    workDir: string,
    homeDir: string,
    trace: any,
    availableSkills: string,
): Promise<AgentResult> {
    const planSpan = trace.span({ name: "Planning-Sonnet-Plan-Review", metadata: { mode: 'plan-only' } });
    const { redactText } = await import('../security/redactor');
    const previousErrors = await redactText(task.additionalFeedback || "");
    const rawPlan = await planPhase(workDir, homeDir, task, availableSkills, previousErrors);
    const plan = rawPlan.replaceAll('<plan>', '').replaceAll('</plan>', '').trim();
    planSpan.end({ output: plan });

    return { mode: 'plan-only', status: 'plan-generated', plan };
}

async function handleExecuteOnlyMode(
    task: Task,
    workDir: string,
    homeDir: string,
    git: any,
    trace: any,
    plan: string,
): Promise<AgentResult> {
    const execSpan = trace.span({ name: "Execution-Sonnet-Approved-Plan", metadata: { mode: 'execute-only' } });
    await executePhase(workDir, homeDir, plan);
    execSpan.end();

    const check = await runPolyglotValidation(workDir);

    if (!check.success) {
        const failureSummary = await summarizeFailurePhase(task, homeDir, check.output);
        return { mode: 'execute-only', status: 'validation-failed', validationOutput: check.output, failureSummary };
    }

    await git.add('.');
    const status = await git.status();

    if (status.staged.length === 0) {
        return { mode: 'execute-only', status: 'no-changes' };
    }

    await git.commit("feat: " + task.title);
    const pushArgs = task.isIteration ? [] : ['--force'];
    await git.push('origin', task.branchName, pushArgs);

    let prUrl: string | null = null;
    if (!task.isIteration) {
        const prBody = await generatePRDescription(workDir, git, task.description || '', check);
        prUrl = await createPullRequest(task.repoUrl, task.branchName, "feat: " + task.title, prBody);
    }

    return { mode: 'execute-only', status: 'executed', prUrl, isIteration: task.isIteration ?? false };
}
