import { logger } from '../infra/logger';
import { setupWorkspace, parseRepoUrl } from "./workspace";
import { runPolyglotValidation, detectProjectLanguages } from "./tools";
import { runClaudeExecution } from '../infra/claude-runner';
import fsPromises from 'node:fs/promises';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import type { SimpleGit } from 'simple-git';
import type { Task, AgentResult } from '../domain/types';
import { noopTracer } from '../domain/tracer-contract';
import type { ITracer } from '../domain/tracer-contract';

// --- TYPES ---

export type { Task } from '../domain/types';

interface IterationContext {
    workDir: string;
    homeDir: string;
    task: Task;
    availableSkills: string;
    git: SimpleGit;
    tracer: ITracer;
}

// --- HELPERS ---

async function summarizeFailurePhase(task: Task, _homeDir: string, errors: string): Promise<string> {
    try {
        const { b } = await import('../infra/baml');
        // Redaction is handled by the BAML proxy before the prompt reaches Claude CLI.
        const result = await b.SummarizeFailure({
            validationOutput: errors.substring(0, 2000),
            attempt: task.attempt,
            maxAttempts: task.maxAttempts,
        });
        return result.summary;
    } catch (e) {
        if (e instanceof Error && e.name === 'RateLimitError') throw e;
        logger.warn({ err: e }, "⚠️ summarizeFailurePhase failed, using fallback message");
        return "Task failed due to persistent validation errors.";
    }
}

function getValidationSummary(output: string): string[] {
    const summary: string[] = [];
    if (output.includes('Biome')) {
        summary.push(output.includes('✓') || output.includes('pass') ? '✅ Biome' : '⚠️ Biome');
    }
    if (output.includes('TSC') || output.includes('TypeScript')) {
        summary.push(output.includes('✓') || output.includes('0 error') ? '✅ TSC' : '⚠️ TSC');
    }
    if (output.includes('Ruff')) {
        summary.push(output.includes('✓') || output.includes('pass') ? '✅ Ruff' : '⚠️ Ruff');
    }
    if (output.includes('Mypy')) {
        summary.push(output.includes('✓') || output.includes('Success') ? '✅ Mypy' : '⚠️ Mypy');
    }
    if (output.includes('Trivy')) {
        summary.push(output.includes('✓') || output.includes('0 vulnerabilities') ? '✅ Trivy' : '⚠️ Trivy');
    }
    return summary;
}

async function generatePRDescription(
    workDir: string,
    git: SimpleGit,
    taskDescription: string,
    validationResult: { success: boolean; output: string; languages?: string[] }
): Promise<string> {
    try {
        const diffStats = await git.diffSummary(['main']);
        const filesChanged = diffStats.files?.length || 0;
        const insertions = diffStats.insertions || 0;
        const deletions = diffStats.deletions || 0;

        const testFiles = diffStats.files?.filter(f =>
            f.file?.match(/\.(test|spec)\.|tests\/|__tests__\//)
        ).length || 0;

        const validationSummary = getValidationSummary(validationResult.output);

        const sections: string[] = [];
        if (taskDescription?.trim()) {
            sections.push(`## Task Description\n\n${taskDescription.trim()}`);
        }

        sections.push(
            `## 📊 Changes Summary\n`,
            `- **Files changed:** ${filesChanged}`,
            `- **Insertions:** +${insertions}`,
            `- **Deletions:** -${deletions}`
        );

        if (testFiles > 0) {
            sections.push(`- **Test files:** ${testFiles} modified/added`);
        }

        if (validationSummary.length > 0) {
            sections.push(
                `\n## ✅ Validation\n`,
                validationSummary.join(' • ')
            );
        }

        sections.push(`\n---\n🤖 Generated by [Ralph Platform](https://github.com/Replikanti/ralph-platform)`);

        return sections.join('\n');
    } catch (error) {
        logger.warn({ err: error }, '⚠️ Failed to generate PR description');
        return taskDescription || 'Implementation completed by Ralph';
    }
}

async function createPullRequest(repoUrl: string, branchName: string, title: string, body: string): Promise<string | null> {
    const { owner, repo } = parseRepoUrl(repoUrl);
    try {
        const { Octokit } = await import("@octokit/rest");
        const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
        
        const response = await octokit.rest.pulls.create({
            owner,
            repo,
            title,
            body,
            head: branchName,
            base: 'main', 
        });
        return response.data.html_url;
    } catch (e: any) {
        logger.error("PR failed: " + e.message);
        return null;
    }
}

export { RateLimitError } from '../infra/claude-runner';

async function listAvailableSkills(workDir: string): Promise<string> {
    // List native commands from .claude/commands so the Planner knows what's available
    const skillsDir = path.join(workDir, '.claude', 'commands');
    try {
        const dirs = await fsPromises.readdir(skillsDir, { withFileTypes: true });
        return dirs
            .filter((d: fs.Dirent) => d.isDirectory())
            .map((d: fs.Dirent) => `- /${d.name}`)
            .join('\n');
    } catch { return "No native commands available."; }
}

async function planPhase(_workDir: string, _homeDir: string, task: Task, availableSkills: string, previousErrors?: string) {
    const { b } = await import('../infra/baml');
    // User-provided fields (title, description) are clean from the queue boundary (server.ts).
    // Runtime-generated fields (previousErrors) are redacted by the BAML proxy before reaching Claude CLI.
    const result = await b.PlanTask({
        title: task.title,
        description: task.description ?? '',
        skills: availableSkills,
        previousErrors: previousErrors ? [previousErrors] : [],
    });
    return result.plan;
}

async function executePhase(workDir: string, homeDir: string, plan: string) {
    const { accountPool } = await import('../infra/account-pool');
    await accountPool.seedCredentials(homeDir).catch((e: any) => {
        logger.warn('⚠️ executePhase: credential seeding failed — ' + e.message);
    });
    const prompt = "You are the Executor. Implement this plan strictly: " + plan + "\n" +
        "RULES: No secrets, stay in sandbox, only necessary files, do not commit.";
    return runClaudeExecution({
        prompt,
        model: 'claude-opus-4-6',
        tools: 'Bash,Read,Edit,FileSearch,Glob',
        timeoutMs: 900_000,
        allowPermissionBypass: true,
    }, workDir, homeDir);
}

const CLAUDE_CACHE_ROOT = process.env.CLAUDE_CACHE_PATH || '/app/claude-cache';

async function syncDirectoryContents(sourceDir: string, targetDir: string, operation: string): Promise<void> {
    if (!fs.existsSync(sourceDir)) return;

    await fsPromises.mkdir(targetDir, { recursive: true });
    try {
        for (const entry of fs.readdirSync(sourceDir)) {
            fs.cpSync(
                path.join(sourceDir, entry),
                path.join(targetDir, entry),
                { recursive: true }
            );
        }
        logger.info(operation + " Claude projects cache");
    } catch (e: any) {
        logger.warn(operation + " failed: " + e.message);
    }
}

async function seedClaudeCache(targetClaudeDir: string) {
    const projectsCache = path.join(CLAUDE_CACHE_ROOT, 'projects');
    const targetProjects = path.join(targetClaudeDir, 'projects');
    await syncDirectoryContents(projectsCache, targetProjects, "Seeded");
}

async function persistClaudeCache(sourceClaudeDir: string) {
    const projectsSource = path.join(sourceClaudeDir, 'projects');
    const targetProjects = path.join(CLAUDE_CACHE_ROOT, 'projects');
    await syncDirectoryContents(projectsSource, targetProjects, "Persisted");
}

async function prepareClaudeSkills(workDir: string, homeDir: string) {

    const targetSkillsDir = path.join(homeDir, '.claude', 'commands');

    const sourceSkillsDir = path.join(workDir, '.claude', 'commands');

    const targetScriptsDir = path.join(homeDir, '.claude', 'scripts');

    const sourceScriptsDir = path.join(workDir, '.claude', 'scripts');



    try {

        if (await fsPromises.stat(sourceSkillsDir).then(() => true).catch(() => false)) {

            await fsPromises.mkdir(targetSkillsDir, { recursive: true });

            await fsPromises.cp(sourceSkillsDir, targetSkillsDir, { recursive: true });

        }

        if (await fsPromises.stat(sourceScriptsDir).then(() => true).catch(() => false)) {

            await fsPromises.mkdir(targetScriptsDir, { recursive: true });

            await fsPromises.cp(sourceScriptsDir, targetScriptsDir, { recursive: true });

        }

        logger.info("Loaded commands into isolated Claude environment");

    } catch (e: any) {

        logger.warn("Failed to load commands: " + e.message);

    }

}





async function runIteration(iteration: number, ctx: IterationContext, previousErrors: string): Promise<{ success: boolean, output?: string, agentResult?: AgentResult }> {
    logger.info("🤖 Iteration " + iteration);

    const rawPlan = await ctx.tracer.span("Planning-Opus-Iter-" + iteration, { iteration }, async () => {
        return planPhase(ctx.workDir, ctx.homeDir, ctx.task, ctx.availableSkills, previousErrors);
    });
    const plan = rawPlan.replaceAll('<plan>', '').replaceAll('</plan>', '').trim();

    await ctx.tracer.span("Execution-Opus-Iter-" + iteration, { iteration }, async () => {
        await executePhase(ctx.workDir, ctx.homeDir, plan);
    });

    const check = await ctx.tracer.span("Validation", { iteration }, async () => {
        return runPolyglotValidation(ctx.workDir);
    });

    if (check.success) {
        logger.info("✅ Validation passed!");
        await ctx.git.add('.');
        const status = await ctx.git.status();
        if (status.staged.length > 0) {
            await ctx.git.commit("feat: " + ctx.task.title);
            const pushArgs = ctx.task.isIteration ? [] : ['--force'];
            await ctx.git.push('origin', ctx.task.branchName, pushArgs);

            let prUrl: string | null = null;
            if (!ctx.task.isIteration) {
                const prBody = await generatePRDescription(ctx.workDir, ctx.git, ctx.task.description || '', check);
                prUrl = await createPullRequest(ctx.task.repoUrl, ctx.task.branchName, "feat: " + ctx.task.title, prBody);
            }
            return { success: true, agentResult: { mode: 'full', status: 'executed', prUrl, isIteration: ctx.task.isIteration ?? false } };
        } else {
            logger.warn("⚠️ No files changed.");
            return { success: true, agentResult: { mode: 'full', status: 'no-changes' } };
        }
    }
    logger.warn("⚠️ Validation failed (Iter " + iteration + "):\n" + check.output);
    return { success: false, output: check.output };
}

async function setupClaudeEnvironment(targetClaudeDir: string, workDir: string, homeDir: string): Promise<string> {
    await fsPromises.mkdir(targetClaudeDir, { recursive: true });
    const sourceClaudeDir = path.join(os.homedir(), '.claude');

    try {
        await copyClaudeCredentials(sourceClaudeDir, targetClaudeDir);
        await configureClaudeSettings(targetClaudeDir);
        await ensureClaudeCredentialsExist(targetClaudeDir);
    } catch (e: any) {
        logger.warn("Seed failed: " + e.message);
    }

    await seedClaudeCache(targetClaudeDir);
    await prepareClaudeSkills(workDir, homeDir);
    return await listAvailableSkills(workDir);
}

async function copyClaudeCredentials(sourceDir: string, targetDir: string): Promise<void> {
    const files = ['.credentials.json', 'settings.json'];
    for (const f of files) {
        const src = path.join(sourceDir, f);
        const dst = path.join(targetDir, f);
        if (fs.existsSync(src)) {
            await fsPromises.copyFile(src, dst);
        }
    }
}

async function configureClaudeSettings(targetClaudeDir: string): Promise<void> {
    const settingsFile = path.join(targetClaudeDir, 'settings.json');
    let settings: any = {};

    if (fs.existsSync(settingsFile)) {
        try {
            settings = JSON.parse(await fsPromises.readFile(settingsFile, 'utf-8'));
        } catch {
            settings = {};
        }
    }

    if (!settings.mcpServers) {
        settings.mcpServers = {};
    }

    settings.mcpServers.toonify = {
        command: "node",
        args: ["/app/dist/mcp-toonify.js"]
    };

    await fsPromises.writeFile(settingsFile, JSON.stringify(settings, null, 2));

    const toonifyConfig = path.join(targetClaudeDir, 'toonify-config.json');
    if (!fs.existsSync(toonifyConfig)) {
        await fsPromises.writeFile(toonifyConfig, JSON.stringify({
            "enabled": true,
            "minTokensThreshold": 50,
            "minSavingsThreshold": 30,
            "skipToolPatterns": ["Bash", "Write", "Edit"]
        }, null, 2));
    }
}

async function ensureClaudeCredentialsExist(targetClaudeDir: string): Promise<void> {
    const credsFile = path.join(targetClaudeDir, '.credentials.json');
    if (!fs.existsSync(credsFile)) {
        await fsPromises.writeFile(credsFile, JSON.stringify({ "token": "dummy", "email": "ralph@duvo.ai" }));
    }
}

async function runFullMode(task: Task, workDir: string, homeDir: string, git: SimpleGit, tracer: ITracer, availableSkills: string, targetClaudeDir: string): Promise<AgentResult> {
    let previousErrors = "";
    for (let i = 0; i < 3; i++) {
        const result = await runIteration(i + 1, { tracer, workDir, homeDir, task, availableSkills, git }, previousErrors);
        await persistClaudeCache(targetClaudeDir);
        if (result.success && result.agentResult) {
            return result.agentResult;
        }
        previousErrors = result.output || "Unknown error";
    }
    const failureSummary = await summarizeFailurePhase(task, homeDir, previousErrors);
    return { mode: 'full', status: 'validation-failed', validationOutput: previousErrors, failureSummary };
}

// Helper to detect task type for Langfuse tracking
function detectTaskType(title: string): string {
    const lower = title.toLowerCase();
    if (lower.includes('fix') || lower.includes('bug')) return 'bugfix';
    if (lower.includes('refactor')) return 'refactor';
    if (lower.includes('test')) return 'test';
    if (lower.includes('doc')) return 'docs';
    return 'feature';
}

export const runAgent = async (task: Task, tracer: ITracer = noopTracer): Promise<AgentResult> => {
    const mode = task.mode || 'full';
    const planReviewEnabled = process.env.PLAN_REVIEW_ENABLED !== 'false';
    const actualMode = (mode === 'full' && planReviewEnabled) ? 'plan-only' : mode;

    logger.info(`🎯 Running agent in mode: ${actualMode}`);

    // Setup workspace first to detect languages
    const { workDir, rootDir, git, cleanup } = await setupWorkspace(task.repoUrl, task.branchName);

    // Detect project languages for tracing
    const detectedLanguages = await detectProjectLanguages(workDir);

    return tracer.span("Ralph-Task", {
        ticketId: task.ticketId,
        mode: actualMode,
        languages: detectedLanguages as unknown[],
        repository: task.repoUrl,
        taskType: detectTaskType(task.title)
    }, async (): Promise<AgentResult> => {
        const homeDir = path.join(rootDir, 'home');
        const targetClaudeDir = path.join(homeDir, '.claude');

        try {
            const availableSkills = await setupClaudeEnvironment(targetClaudeDir, workDir, homeDir);

            if (actualMode === 'plan-only') {
                return await handlePlanOnlyMode(task, workDir, homeDir, tracer, availableSkills);
            }

            if (actualMode === 'execute-only') {
                if (!task.existingPlan) {
                    throw new Error("execute-only mode requires existingPlan");
                }
                return await handleExecuteOnlyMode(task, workDir, homeDir, git, tracer, task.existingPlan);
            }

            return await runFullMode(task, workDir, homeDir, git, tracer, availableSkills, targetClaudeDir);
        } finally {
            cleanup();
        }
    });
};

async function handlePlanOnlyMode(
    task: Task,
    workDir: string,
    homeDir: string,
    tracer: ITracer,
    availableSkills: string,
): Promise<AgentResult> {
    // additionalFeedback is already redacted at the queue boundary (server.ts).
    const previousErrors = task.additionalFeedback || "";
    const rawPlan = await tracer.span("Planning-Opus-Plan-Review", { mode: 'plan-only' }, async () => {
        return planPhase(workDir, homeDir, task, availableSkills, previousErrors);
    });
    const plan = rawPlan.replaceAll('<plan>', '').replaceAll('</plan>', '').trim();

    return { mode: 'plan-only', status: 'plan-generated', plan };
}

async function handleExecuteOnlyMode(
    task: Task,
    workDir: string,
    homeDir: string,
    git: SimpleGit,
    tracer: ITracer,
    plan: string,
): Promise<AgentResult> {
    await tracer.span("Execution-Opus-Approved-Plan", { mode: 'execute-only' }, async () => {
        await executePhase(workDir, homeDir, plan);
    });

    const check = await runPolyglotValidation(workDir);

    if (!check.success) {
        const failureSummary = await summarizeFailurePhase(task, homeDir, check.output);
        return { mode: 'execute-only', status: 'validation-failed', validationOutput: check.output, failureSummary };
    }

    await git.add('.');
    const status = await git.status();

    if (status.staged.length === 0) {
        return { mode: 'execute-only', status: 'no-changes' };
    }

    await git.commit("feat: " + task.title);
    const pushArgs = task.isIteration ? [] : ['--force'];
    await git.push('origin', task.branchName, pushArgs);

    let prUrl: string | null = null;
    if (!task.isIteration) {
        const prBody = await generatePRDescription(workDir, git, task.description || '', check);
        prUrl = await createPullRequest(task.repoUrl, task.branchName, "feat: " + task.title, prBody);
    }

    return { mode: 'execute-only', status: 'executed', prUrl, isIteration: task.isIteration ?? false };
}
